spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        System.out.print로 찍기때문에 지양
#        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
